services:
  video-loop-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:latest
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - /tmp/video-loop-source-downloads:/tmp/video-loop-source-downloads
    environment:
      LOCATION: https://eu-central-1.linodeobjects.com/savant-data/demo/Free_City_Street_Footage.mp4
      DOWNLOAD_PATH: /tmp/video-loop-source-downloads
      ZMQ_ENDPOINT: dealer+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      SOURCE_ID: test
      SYNC_OUTPUT: False
    entrypoint: /opt/savant/adapters/gst/sources/video_loop.sh

  cloud-pin-client:
    build:
      context: ../..
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ssl:/root/ssl
    depends_on:
      ca:
        condition: service_healthy
    command: mode=client
    environment:
      WEBSOCKETS_SSL_CA_FILE: /root/ssl/demoCA/cacert.pem
      WEBSOCKETS_SSL_CERT_FILE: /root/ssl/cloud-pin-client.pem
      WEBSOCKETS_SSL_KEY_FILE: /root/ssl/cloud-pin-client.key
      WEBSOCKETS_ENDPOINT: wss://cloud-pin-server:8080/
      WEBSOCKETS_API_KEY: secret_token
      ZMQ_SRC_ENDPOINT: bind:ipc:///tmp/zmq-sockets/input-video.ipc
      ZMQ_SRC_RESULTS_QUEUE_SIZE: 1000
      ZMQ_SINK_ENDPOINT: connect:ipc:///tmp/zmq-sockets/output-video.ipc
      ZMQ_SINK_MAX_INFLIGHT_MESSAGES: 1000
      METRICS_PROMETHEUS_ENDPOINT: http://0.0.0.0:8081/
      IO_TIMEOUT: 0.002

  cloud-pin-server:
    build:
      context: ../..
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ssl:/root/ssl
    depends_on:
      ca:
        condition: service_healthy
    command: mode=server
    environment:
      WEBSOCKETS_ENDPOINT: wss://cloud-pin-server:8080/
      WEBSOCKETS_API_KEY: secret_token
      WEBSOCKETS_SSL_CA_FILE: /root/ssl/demoCA/cacert.pem
      WEBSOCKETS_SSL_CERT_FILE: /root/ssl/cloud-pin-server.pem
      WEBSOCKETS_SSL_KEY_FILE: /root/ssl/cloud-pin-server.key
      ZMQ_SRC_ENDPOINT: bind:ipc:///tmp/zmq-sockets/intermediate-video.ipc
      ZMQ_SRC_RESULTS_QUEUE_SIZE: 1000
      ZMQ_SINK_ENDPOINT: connect:ipc:///tmp/zmq-sockets/intermediate-video.ipc
      ZMQ_SINK_MAX_INFLIGHT_MESSAGES: 1000
      METRICS_PROMETHEUS_ENDPOINT: http://0.0.0.0:8082/
      IO_TIMEOUT: 0.002

  ca:
    build:
      context: ../_shared/ssl/
      dockerfile_inline: |
        FROM debian:trixie
        RUN apt-get update && apt-get install -y openssl
    volumes:
      - ../_shared/ssl/prepare_certs.sh:/root/prepare_certs.sh
      - ssl:/root/ssl
    healthcheck:
      test: [CMD, test, -e, cloud-pin-server.pem, -a, -e cloud-pin-server.pem]
      interval: 60s
      start_period: 30s
      start_interval: 2s
    environment:
      SERVER_NAME: cloud-pin-server
      CLIENT_NAME: cloud-pin-client
    working_dir: /root/ssl/
    entrypoint: sh -c
    command:
      - >
        /root/prepare_certs.sh;
        sleep infinity;

  null_zmq_reader:
    image: ghcr.io/insight-platform/savant-rs-py314:savant-latest
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ./null_zmq_reader.py:/null_zmq_reader.py
    healthcheck:
      test: ["CMD", "test", "-e", "/tmp/ready"]
      interval: 2s
      start_period: 30s
    environment:
      ZMQ_ENDPOINT: router+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      READY_PATH: /tmp/ready
    command: ["python", "/null_zmq_reader.py"]

  benchmark:
    image: ghcr.io/insight-platform/savant-rs-py314:savant-latest
    volumes:
      - ./reports/:/tmp/reports/
      - ./benchmark_report.py:/benchmark_report.py
    environment:
      DURATION: 60
      REPORT_PATH: /tmp/reports/no-sync-stream.txt
      CLIENT_METRICS_PROMETHEUS_ENDPOINT: http://cloud-pin-client:8081/metrics
      SERVER_METRICS_PROMETHEUS_ENDPOINT: http://cloud-pin-server:8082/metrics
    depends_on:
      video-loop-source:
        condition: service_started
      cloud-pin-client:
        condition: service_started
      cloud-pin-server:
        condition: service_started
      null_zmq_reader:
        condition: service_healthy
    command: ["python", "/benchmark_report.py"]

volumes:
  zmq_sockets:
  ssl:
